### ISSUE TITLE
Fix memory issues

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#1]
I would recommend running your program through the address sanitizer: it detects all kind of memory issues and leaks:

https://github.com/mehemmedv/DB_Imp_Seminar/blob/836621698043aaebe149080a9ae018ee8af0775a/CMakeLists.txt#L8

-->  cmake -DCMAKE_BUILD_TYPE=Debug

**Comment by mehemmedv** [comment]
Resolved.
