### ISSUE TITLE
Add Catch2 Tests

### ISSUE THREAD

**Issue by jboettcher** [mehemmedv/DB_Imp_Seminar#10]
You already have some nice consistence checks between the different graph layouts.

It would be nice though to integrate a "real" test framework, especially if you plan to extend the work to guided research/master thesis and the underlying graph structures become little bit more complex.
For instance, you could have some small test graphs (only some nodes) and check if the result is correct.

For the seminar, it's up to you if you already add it, since you have already done more than enough coding for the scope of a seminar.

**Comment by jboettcher** [comment]
https://raw.githubusercontent.com/CatchOrg/Catch2/master/single_include/catch.hpp 

https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#top

**Comment by mehemmedv** [comment]
Done.
