### ISSUE TITLE
Add std::vector (arraylist instead of linked list) implementation for ALGraph

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#11]
https://github.com/mehemmedv/DB_Imp_Seminar/blob/11436c67cec3342688a415d8f69b7786e7b79d7f/include/ALGraph.h#L14

According to the specs: a std::list in c++ is usually a doubly linked list, which is really update friendly but not very cache efficient.

Could you add a second variant of the ALGraph using std::vectors (lists backed by arrays)?
I would expect them to perform better in most workloads.

**Comment by mehemmedv** [comment]
Resolved.

**Comment by mehemmedv** [comment]
Seems like, it does better on dfs and dijkstra, but not on bfs.

**Comment by bottey** [comment]
that's surprising: how big is the difference?

**Comment by mehemmedv** [comment]
it is actually very little.

**Comment by bottey** [comment]
mhh, weird. Maybe the graph size is too small to get meaningful results? 
In my opinion it should never be slower than the linked list implementation.

**Comment by mehemmedv** [comment]
Hm, that could be of course. Better would be to try at the server, as RAM of my machine is just 8GB.
