### ISSUE TITLE
move sum print outs to the end of algorithm

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#12]
https://github.com/mehemmedv/DB_Imp_Seminar/blob/3343ff2a17d371e2986ce65d9bccb75e1a96850d/src/GraphAlgo.cpp#L35

you should move all the printouts to the end of the algorithm, otherwise the performance suffers from all the printouts...and the console will be flooded

--> only one print/per algorithm

Sorry my last issue on that was little bit unclear;)

**Comment by bottey** [comment]
Another good thing to know about _std::endl vs using << "\n"_ is that std::endl also flushes the output buffer, which can also hurt the performance a lot, when you are doing it constantly.

**Comment by mehemmedv** [comment]
Resolved
