### ISSUE TITLE
Run workload with mutations (adding of edges)

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#15]
You've already implemented adding of edges, right?
If so, you could easily run a mixed workload:

Let's say your set of operations is DFS, BFS, and Dijkstra.
Run them round-robin and every x-th operation is the addition of a random edge.

This workload should cause some troubles for CSR and help us to justify our title "how good is CSR really" :)

**Comment by mehemmedv** [comment]
Resolved. There was a bug on add_edge method, as we agreed to change the type from int to uint64_t. Now it works well. I also changed the generation of graph a little bit, we can specify the number of nodes and edges in the arguments and also one more thing additional random edges at the end of files which can be used for mixed workload.

**Comment by bottey** [comment]
very nice! :+1:
