### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#16]
size_t getCurrentRSS() {
   long rss = 0L;
   FILE fp = NULL;
   if ((fp = fopen("/proc/self/statm", "r")) == NULL)
      return (size_t)0L; / Can't open? /
   if (fscanf(fp, "%s%ld", &rss) != 1) {
      fclose(fp);
      return (size_t)0L; / Can't read? /
   }
   fclose(fp);
   return (size_t)rss * (size_t)sysconf(_SC_PAGESIZE);
}

**Comment by mehemmedv** [comment]
Resolved.
