### ISSUE TITLE
sorted performance

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#17]
maybe we need a more real world graph (with neighbors) to get cache benefits

**Comment by mehemmedv** [comment]
with more neighbors(>100), we can't get the benefit of cache. I think it is obvious, with less neighbors(<60) we can get the benefit, I tried it for 10^5 nodes and each with 50 neighbors and tried dfs 2000 times, just to see the difference. the difference is quite big actually :) we can say something about that now :)
