### ISSUE TITLE
ART

### ISSUE THREAD

**Issue by jboettcher** [mehemmedv/DB_Imp_Seminar#19]
Papers and synchronized:
https://github.com/flode/ARTSynchronized/

Original:
https://db.in.tum.de/~leis/index/ART.tgz?lang=en

Key 16 Bytes = NodeA,NodeB
Key --> EdgeId

Iterate over neighbors of nodeA:
lookupPrefix(nodeA (key), 8 (length))

Insert, Delete edges (-->insert, delete)

Array of edges weights:
weights[edgeA] --> weight of edgeA

Edge Array:
Every edge gets its own (incremental) id
Store mapping of edgeId -> (FirstNode), Second Node

foldKey: edgeId --> key: edgeArray[edgeId]

**Comment by bottey** [comment]
std::vector<stuct NodeA,NodeB> == EdgeArray

Constructor:
takes the foldKey unction

Insert edge:
1. create edge record in edgeArray: (nodeA, nodeB)
2. call insert on ART: insert(key==nodeAnodeB, value==id of edgeRecord)

**Comment by mehemmedv** [comment]
Done.
