### ISSUE TITLE
Add some dummy calculation to BFS and DFS

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#3]
https://github.com/mehemmedv/DB_Imp_Seminar/blob/836621698043aaebe149080a9ae018ee8af0775a/src/GraphAlgo.cpp#L32

If the compiler is clever enough, it might simply optimize the entire code away, as it doesn't really do work.
You could do some aggregation of the edge weights to make sure that this cannot happen.

Like calculate the sum of the edge weights, etc.

**Comment by mehemmedv** [comment]
Resolved.
