### ISSUE TITLE
Use 64 bit 

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#4]
https://github.com/mehemmedv/DB_Imp_Seminar/blob/836621698043aaebe149080a9ae018ee8af0775a/include/CSRGraph.h#L12

Real world graphs can be very large: thus, it would make sense to use 64 bit unsingned ints instead of signed ints.

We typically use uint64_t (#include <stdint.h>)

**Comment by mehemmedv** [comment]
Resolved.
