### ISSUE TITLE
Design of a workload 

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#5]
=== I think this might be out of the scope of the seminar, but if we want we could investigate it in future work (guided research/master thesis) ===

In future, we want to evaluate the "changability" of the different layouts:
Therefore it would make sense to have a benchmark for it.

You could check if there is already a suitable benchmark in the literature, or define one yourself.
It would be nice to have some parameters one could adjust for benchmarking like:
 - ratio of edges added
 - ratio of nodes added
 - ratio of deletions
 - ratio of algorithms/queries

**Comment by mehemmedv** [comment]
Yes, we can better discuss it in your office, when I am back.
