### ISSUE TITLE
Dijkstra's typo :p

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#7]
There's is a typooooooooo :dagger: 

https://github.com/mehemmedv/DB_Imp_Seminar/blob/836621698043aaebe149080a9ae018ee8af0775a/src/GraphAlgo.cpp#L92

And I would recommend using uint64_t instead of long long because it is a little bit nicer ;)

**Comment by mehemmedv** [comment]
Resolved.
