### ISSUE TITLE
Memory bug

### ISSUE THREAD

**Issue by bottey** [mehemmedv/DB_Imp_Seminar#8]
When I run the ./DB_Generator out of a Debug build I always get a global-buffer-overflow
Note, that the address_sanitizer is only activated in the debug build.. thus you do not run into this error on a normal (release) build.

Could you take a look at it?

> =================================================================
> ==5615==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5648c8fb1d08 at pc 0x5648c8d74143 bp 0x7ffd6436ad40 sp 0x7ffd6436ad30
> READ of size 8 at 0x5648c8fb1d08 thread T0
>     #0 0x5648c8d74142 in std::vector<int, std::allocator<int> >::push_back(int const&) /usr/include/c++/6/bits/stl_vector.h:916
>     #1 0x5648c8d7392d in main /home/jan/Code/graphs/DB_Imp_Seminar/tests/random_graph_generator.cpp:35
>     #2 0x7fcb39e3c3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
>     #3 0x5648c8d73519 in _start (/home/jan/Code/graphs/DB_Imp_Seminar/build/debug/DB_Generator+0x1519)

**Comment by mehemmedv** [comment]
Resolved.
