### ISSUE TITLE
Related Work: Mutable Graph layouts

### ISSUE THREAD

**Issue by jboettcher** [mehemmedv/DB_Imp_Seminar#9]
Here is some related work:

- STINGER [1]: a mutable graph container that can handle streaming
updates which can be inserted in parallel
- LLAMA [2]: is a recent effort to extend CSR with version support
- AsGraph [3]: work of Michael Haubenschild (currently PhDStudent @ Tableau/TU Munich) about mutable graphs. AsGraph is already outdated and not in use anymore. The paper has a nce structures and gives a good overview though

[1] D. Ediger, R. McColl, E. J. Riedy, and D. A. Bader.
STINGER: high performance data structure for streaming
graphs. In IEEE Conference on High Performance Extreme
Computing, HPEC 2012, Waltham, MA, USA, September
10-12, 2012, pages 1–5, 2012

[2]  P. Macko, V. J. Marathe, D. W. Margo, and M. I. Seltzer.
LLAMA: efficient graph analytics using large multiversioned
arrays. In 31st IEEE International Conference on Data
Engineering, ICDE 2015, Seoul, South Korea, April 13-17,
2015, pages 363–374, 2015.

[3] https://event.cwi.nl/grades/2016/08-Haubenschild.pdf

**Comment by mehemmedv** [comment]
Done.
